// 54-cotizador-prestamos-react/src/App.jsx
import { useState } from "react"
import Header from "./components/header"

function App() {
    const cantidadInicial = 10000;
    const MIN = 0;
    const MAX = 20000;
    const STEP = 100;
    const [cantidad, setCantidad] = useState(cantidadInicial);
    
    function handleChange(e) {
        setCantidad(parseInt(e.target.value));
    }

    return (
        <div className="my-20 max-w-lg mx-auto bg-white shadow p-10">
            <Header/>

            <input 
            type="range"
            className="w-full h-6 bg-gray-200 accent-lime-500 hover:accent-lime-600"
            onChange={ handleChange }
            min={MIN}
            max={MAX}
            value={cantidad}
            step={STEP}
            name="" 
            id="" />
            
            <p className="text-center my-10 text-5xl font-extrabold text-indigo-600">{ cantidad }</p>
        </div>
    )
}

export default App

// 55-cotizador-prestamos-vue/src/App.vue
<script setup>
    import { ref } from 'vue';
    import Header from './components/Header.vue';

    const MIN = 0;
    const MAX = 20000;
    const STEP = 100;

    const cantidad = ref(MIN);
    cantidad.value = MAX / 2;
    
    function handleChange(e) {
        cantidad.value = +e.target.value;
    }
</script>

<template>
    <div class="my-20 max-w-lg mx-auto bg-white shadow p-10">
        <Header />

        <div class="my-5">
            <input 
                type="range"
                class="w-full bg-gray-200 accent-lime-500 hover:accent-lime-600"
                @input="handleChange"
            >
            <p>{{cantidad}} €</p>
            <p v-text="`${cantidad} €`"></p>
        </div>
    </div>
</template>
